apiVersion: v1
kind: Service
metadata:
  name: Streamlit-nodeport
spec:
  type: NodePort
  selector:
    app: Streamlit
  ports:
  - protocol: TCP
    port: 8501
    targetPort: 8501
    nodePort: 30080
    